[book]
title = "The Juvix Book"
authors =  [ "Jonathan Prieto-Cubides" , "Jan Mas Rovira" , "Paul Cadman" , "Lukasz Czajka" ]
language = "en"
multilingual = false
src = "docs/md/"

[build]
build-dir = "_docs"
create-missing = true

[output.html]
mathjax-support = true

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
